live_config_reload = true

[colors.primary]
background = "#010C19"

# Tokyonight night
# background = '0x1a1b26'
# foreground = '0xc0caf5'
#
# [colors.normal]
# black = '0x15161e'
# red = '0xf7768e'
# green = '0x9ece6a'
# yellow = '0xe0af68'
# blue = '0x7aa2f7'
# magenta = '0xbb9af7'
# cyan = '0x7dcfff'
# white = '0xa9b1d6'
#
# [colors.bright]
# black = '0x414868'
# red = '0xf7768e'
# green = '0x9ece6a'
# yellow = '0xe0af68'
# blue = '0x7aa2f7'
# magenta = '0xbb9af7'
# cyan = '0x7dcfff'
# white = '0xc0caf5'
#
# [[colors.indexed_colors]]
# index = 16
# color = '0xff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '0xdb4b4b'


[cursor.style]
shape = "Beam"

[font.bold]
family = "JetBrainsMonoNerdFontPropo"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontPropo"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNerdFontPropo"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNerdFontPropo"
style = "Regular"

[window]
decorations = "none"
opacity = 1

[window.dimensions]
# columns = 104
# lines = 30
columns = 150
lines = 35

[window.padding]
x = 10
y = 5
